### ISSUE TITLE
some result images come out with NaN values

### ISSUE THREAD

**Issue by NeutronNA** [neutronimaging/KipTool#16]
[Proc04-1to5.zip](https://github.com/neutronimaging/KipTool/files/7379580/Proc04-1to5.zip)
Dear all,
I am learning about image analysis with kiptool.
I have run  kiptool successfully but several times it has happened that the result from the kiptool analysis is some images with NaN values and some corrected images. I wonder why this happens as the same images are used for correction for the whole set of projections but some come out ok and others don´t. Any ideas/suggestions for me to check?

**Comment by anderskaestner** [comment]
The NaNs are usually an effect of unstable conditions. In the ISS filter, it usually helps to reduce alpha and lambda. Also, the tau can be reduced, but then you need to increase the iterations to achieve the same filter effect. NaNs when you use the BB correction are the consequence of log(negative value). Try cropping the image and reduce the FOV for the bb's to have all in regions that have a reasonable transmission (>10%).

**Comment by NeutronNA** [comment]
ok, solved!
