### ISSUE TITLE
Shut down of kiptool when loading BB

### ISSUE THREAD

**Issue by NeutronMB** [neutronimaging/KipTool#23]
Hi everyone, 

I started with processing of my images with Kiptool. However, during configuration of the BB log norm (imaging.Modules), the program shuts down. It is when I upload the second BB images in the tab 'BB images'. At the same time, after uploading the first BB image, i see no preview image at the bottom (even after pressing preview, nothing happens).  
The program runs on a Windows 10 - pc. The BB image without specimens is 15.9 MB and the BB of the samples is 6.9 MB. I tried i already with different BB images (taken at different times during the tests) but the problem keeps happening. 

Hopefully, someone can help me out with the problem. 

kind regards
Michiel

**Comment by anderskaestner** [comment]
Can you please tell me which version you are using? [Help]->[About]
Do I understand correctly that you use different image sizes? This will not work.

**Comment by NeutronMB** [comment]
I'm using version 5.12.5. 
The files are of the same image size, but the first one was in 16-bits in stead of 8. 
I changed this type but have still the same result.
